const VER_SCENARIO_IGARI = "0.6.0"; // バージョン更新（ステージ6のシナリオ刷新およびエンディングの追加）

window.scenarios = window.scenarios || {};

scenarios.igari = {
    'opening': [
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 10, speaker: '猪狩', text: '魔女の里かー。俺も仕事じゃなきゃ行きたかったな', delay: 60, bgm: 'relax' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 0, speaker: '柊', text: 'まあまあ、今回は修行で行くんだし' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 1, speaker: '柊', text: '一緒に行ってもどこへも行けないよ？' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 3, speaker: '猪狩', text: '知的好奇心ってやつさ' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 2, speaker: '猪狩', text: 'この科学の時代に魔女の里だろ？' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 10, speaker: '猪狩', text: '磁場とか放射線量とか測定してぇー' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 5, speaker: '柊', text: 'でたよ、科学バカ・・・' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 6, speaker: '柊', text: '（小声）まあ、そんなとこも好きだけど・・・' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', text: 'なんか言ったか？' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 9, speaker: '柊', text: 'ううん。じゃあ、行ってくる' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 1, speaker: '猪狩', text: 'ああ。気をつけて' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 0, speaker: '柊', text: '・・・あのさ、俊基' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 7, speaker: '柊', text: '一ヶ月で浮気とかしたら魂ごと滅ぼすから' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 9, speaker: '猪狩', text: 'だ、大丈夫だって' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 10, speaker: '柊', text: '冗談よ。じゃねー' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 10, effect: 'slideOutLeft', text: '' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: '全く。魔女ってやつはみんなあんなに嫉妬深いのかな' },
        { bg: 'airport.png', place: 'Airport', time: '2026.04', effect: 'shake', text: '', bgm: 'stop' },
        { bg: 'breakplane.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 4, speaker: '猪狩', text: 'あれは！　千華の乗った飛行機！', bgm: 'dark' },
        { bg: 'breakplane.png', place: 'Airport', time: '2026.04', character: 'igari02.png', spriteIndex: 4, speaker: '猪狩', text: '千華！　千華ァーーーー！' },
        { bg: 'breakplane.png', place: 'Airport', time: '2026.04', effect: 'whiteout', text: '' }
    ],
    'kagami_arrival': [
        { bg: 'room.png', place: 'Room', time: '2025.04', se: 'alarm.mp3', text: '' },
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 9, speaker: '猪狩', text: 'はっ・・・夢？', bgm: 'relax' },
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 8, speaker: '猪狩', text: 'てか、俺なんで家にいるんだよ！　いま何時だ、仕事が・・・' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', text: '' },
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', text: '・・・2025年4月2日？' },
        { bg: 'room.png', place: 'Room', time: '2025.04',item: 'phone2.png', se: 'vibration.mp3', text: '' },
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: 'はい、猪狩ですが' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: '猪狩俊基だな。私は異世界保険組合の者だ' },
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: 'いせかい・・・保険組合？' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: '科学文明軍という異世界人が空港で爆破テロを行った' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: 'これは、異世界条項47条違反でね' },
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: 'あのなあ。今どき特殊詐欺でもまだマシな嘘をつくぞ？' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: 'また恋人を失いたいのか？', bgm: 'stop' },
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: '！', bgm: 'dark' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: 'あれは夢などではない' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: 'あの未来を防ぐため、我々は１年間を巻き戻したのだ' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: 'もし君が未来を変えたければ' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: '科学文明軍と戦い、彼らを撃破しなくてはならない' },
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 9, speaker: '猪狩', text: 'いや、でもどうやって' },
        { bg: 'room.png', place: 'Room', time: '2025.04', effect: 'shake', text: '' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: 'とぼけるのはやめるんだな、猪狩俊基' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: '君は異世界から転移した天才科学者、猪狩隆盛の息子だろう？' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: '戦う術を持っていないとは言わせないぞ' },
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: '何故それを・・・' },
        { bg: 'room.png', place: 'Room', time: '2025.04', item: 'phone3.png', speaker: '？？？', text: 'そうだな。生き残ったら説明してやってもいい'},
        { bg: 'room.png', place: 'Room', time: '2025.04', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: 'ふざけやがって・・・' },
        { bg: 'igni.png', place: 'Room', time: '2025.04', speaker: '猪狩', text: 'イグニッション' }
    ],
    1: {
        stgId: 'kagami',
        adv: [],
        pre_stg: [],
        post_stg: [
            { bg: 'breakufo.png', place: 'Airport', time: '2025.04', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: 'いいだろう。第１関門は合格だ', bgm: 'relax' },
            { bg: 'breakufo.png', place: 'Airport', time: '2025.04', character: 'igari02.png', spriteIndex: 4, speaker: '猪狩', text: '合格・・・？　てか、その声！' },
            { bg: 'breakufo.png', place: 'Airport', time: '2025.04', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '私が君をタイムリープさせた' },
            { bg: 'breakufo.png', place: 'Airport', time: '2025.04', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '異世界保険組合の各務（かがみ）だ' }
        ]
    },
    2: {
        stgId: 'hiragi',
        adv: [
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: '俊基。その女、誰？', delay: 60, isRight: false, bgm: 'relax' },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 13, speaker: '猪狩',character2: 'kagami.png', spriteIndex2: 0, text: '千華!?　お前どうしてここに！', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 0, speaker: '柊', text: '俊基の生命エネルギーが少し減ったのを感じたの', isRight: false },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: '心配になって来てみたら、なんか女といるし', isRight: false },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 12, character2: 'kagami.png', spriteIndex2: 0, speaker: '猪狩', text: '俺の生命エネルギーなんてモニタリングしてんのか!?', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 9, speaker: '柊', text: '女と二人きり、身体は無事で、エネルギー消費・・・', isRight: false },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 9, character2: 'kagami.png', spriteIndex2: 9, speaker: '猪狩', text: '待て、なんか壮大な誤解をしてるぞお前', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 12, speaker: '柊', text: '・・・浮気だ', isRight: false },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 12, character2: 'kagami.png', spriteIndex2: 0, speaker: '猪狩', text: 'お、おい千華！', isRight: true },
            { bg: 'breakufo.png', place: "Cika's territory", character: 'hiragi01.png', spriteIndex: 13, speaker: '柊', text: '浮気だーーーー！', effect: 'shake', isRight: false, bgm: 'stop' },
            { bg: 'breakufo.png', maskBg: 'darkcandle.png', maskDelay: 90, character: 'hiragi01.png', spriteIndex: 13, effect: 'shake', text: '', isRight: false, bgm: 'dark' }
        ],
        pre_stg: [
            { bg: 'darkcandle.png', character: 'kagami.png', spriteIndex: 14, speaker: '各務', text: 'なんだ？　何が起こった!?', isRight: true },
            { bg: 'darkcandle.png', character: 'igari02.png', spriteIndex: 4, speaker: '猪狩', text: '魔女の結界だ！　千華のやつブチ切れやがった！', isRight: true },
            { bg: 'darkcandle.png', character: 'hiragi01.png', spriteIndex: 11, speaker: '柊', text: 'もう殺す。その女も、俊基も', isRight: false },
            { bg: 'darkcandle.png', character: 'hiragi01.png', spriteIndex: 3, speaker: '柊', text: '両方殺して私も死ぬ！', isRight: false, effect: 'shake' },
            { bg: 'darkcandle.png', character: 'igari02.png', spriteIndex: 12, character2: 'kagami.png', spriteIndex2: 2, speaker: '各務', text: 'おい、どうするんだ？', isRight: true },
            { bg: 'darkcandle.png', character: 'igari02.png', spriteIndex: 5, character2: 'kagami.png', spriteIndex2: 6, speaker: '猪狩', text: '死なん程度に攻撃して落ち着かせるしかない', isRight: true },
            { bg: 'darkcandle.png', character: 'igari02.png', spriteIndex: 0, character2: 'kagami.png', spriteIndex2: 2, speaker: '各務', text: '世界を書き換えるようなバケモン相手にそんな芸当、できんのか？', isRight: true },
            { bg: 'darkcandle.png', character: 'igari02.png', spriteIndex: 7, character2: 'kagami.png', spriteIndex2: 6, speaker: '猪狩', text: 'やらなきゃならんだろ。じゃなきゃ、助ける予定の女に殺されちまう！', isRight: true },
            { bg: 'darkcandle.png', character: 'igari02.png', spriteIndex: 5, character2: 'kagami.png', spriteIndex2: 2, speaker: '各務', text: '面倒なことになったな・・・', isRight: true },
            { bg: 'darkcandle.png', character: 'igari02.png', spriteIndex: 11, character2: 'kagami.png', spriteIndex2: 9, speaker: '各務', text: '仕方ない。私も手伝おう', isRight: true },
            { bg: 'darkcandle.png', character: 'igari02.png', spriteIndex: 0, character2: 'kagami.png', spriteIndex2: 0, speaker: '猪狩', text: '助かる！', isRight: true }
        ],
        post_stg: [
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 1, speaker: '柊', text: 'あれ？　俊基？', isRight: false, bgm: 'relax' },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: 'やっと目ぇ覚めやがったか', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 6, speaker: '柊', text: 'えと、私・・・やっちゃった？', isRight: false },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: '魔界が発生してた。で、使い魔をぶん殴ったとこだ', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 6, speaker: '柊', text: 'ごめんねぇ、俊基', isRight: false },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 3, speaker: '猪狩', text: 'また暴走しないように言っとくぞ', isRight: true },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '俺が大切なのはお前だけだ。忘れんな', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 6, speaker: '柊', text: '俊基ー！', isRight: false },
            { bg: 'breakufo.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: 'あー、話は済んだか？', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 8, speaker: '柊', text: 'あっ、間女！', isRight: false },
            { bg: 'breakufo.png', character: 'kagami.png', spriteIndex: 13, speaker: '各務', text: '違う！　私は異世界保険組合の営業だ！', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 3, speaker: '柊', text: '厨二病を拗らせてるのね', isRight: false },
            { bg: 'breakufo.png', character: 'kagami.png', spriteIndex: 3, speaker: '各務', text: '貴様、歴史から消滅させてやろうか', isRight: true },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: 'まあまあ、二人とも落ち着いて', isRight: true },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: 'それより千華。お前、俺に黙ってることあるだろ', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 1, speaker: '柊', text: 'んんー？　ないけどぉ？', isRight: false },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: '１年後にお前が死ぬ運命だということもか', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 11, speaker: '柊', text: '・・・っ！　どうしてそれを', isRight: false },
            { bg: 'breakufo.png', character: 'igari02.png', spriteIndex: 5, speaker: '猪狩', text: '１年後の世界で、お前が乗った飛行機が爆破されるのを見たからだよ', isRight: true },
            { bg: 'breakufo.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'だが、そのタイミングでの君の死は不都合でね', isRight: true },
            { bg: 'breakufo.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '私がこの世界を１年間巻き戻したというわけだ', isRight: true },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 8, speaker: '柊', text: 'ちょっと待って。運命見てみる・・・', isRight: false },
            { bg: 'breakufo.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: 'んんーー？　変わってないわよ', isRight: false },
            { bg: 'breakufo.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '世界を変えるのは簡単なことじゃない', isRight: true },
            { bg: 'breakufo.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '協力者が必要だ。ついてこい', isRight: true }
        ]
    },
    3: {
        stgId: 'shiina',
        adv: [
            { bg: 'hospital.png', place: 'Hospital', time: '2025.05', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', text: '・・・病院？', delay: 60, isRight: true, bgm: 'relax' },
            { bg: 'hospital.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: 'こんなところに助っ人がいるの？', isRight: true },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '助っ人でもあり、助けるべき人物でもある', isRight: true },
            { bg: 'hospital.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: 'なんだそりゃ', isRight: true },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '我々、異世界保険組合が時間を巻き戻した理由', isRight: true },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '魔女、柊千華の暗殺そして・・・', isRight: true },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 1, speaker: '椎名', text: '各務さん、いらっしゃってたんですね', isRight: false },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 2, speaker: '椎名', text: 'ご挨拶頂ければ、お迎えに上がりましたのに', isRight: false },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '君が忙しいのは承知しているからな', isRight: true },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '実は今日、紹介したい人がいてね', isRight: true },
            { bg: 'hospital.png', character: 'hiragi01.png', spriteIndex: 9, speaker: '柊', text: 'しい・・・な？', isRight: true },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '紹介しよう。椎名護くんだ', isRight: true },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '彼もまた、１年後に命を落とすことになって・・・', isRight: true },
            { bg: 'hospital.png', character: 'hiragi01.png', spriteIndex: 15, speaker: '柊', text: 'あーーーー！　椎名家の跡目！', effect: 'shake', isRight: true },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 2, speaker: '椎名', text: 'そういう君は、魔女の柊さん', isRight: false },
            { bg: 'hospital.png', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', text: '知り合いか？', isRight: true },
            { bg: 'hospital.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: '知り合いも何も！　魔女の天敵よ！', isRight: true },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 1, speaker: '椎名', text: '心外だな。僕らは表立って敵対するつもりはないんだよ', isRight: false },
            { bg: 'hospital.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '向こうは自覚がないようだが？', isRight: true },
            { bg: 'hospital.png', character: 'hiragi01.png', spriteIndex: 15, speaker: '柊', text: '椎名家はね！　魔法を無効化する能力・・・むぐっ', isRight: true },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 8, speaker: '椎名', text: '勤務先で大声出さないで下さいよ', isRight: false },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '椎名くん、それで話を戻すが・・・', isRight: true },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 0, speaker: '椎名', text: 'お断りします', isRight: false },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: 'なんだって？', isRight: true },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 10, speaker: '椎名', text: '僕自身は家業を継いでないのでわかりませんが', isRight: false },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 1, speaker: '椎名', text: '魔女と椎名家の確執は聞いてますから', isRight: false },
            { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: 'いや、しかしな', isRight: true },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 10, speaker: '椎名', text: '例え僕がいいと言っても、仮面が何というか', isRight: false },
            { bg: 'hospital.png', character: 'igari02.png', spriteIndex: 5, speaker: '猪狩', text: '俺からも頼む。もう大切な人を失いたくない', isRight: true },
            { bg: 'hospital.png', character: 'hiragi01.png', spriteIndex: 6, speaker: '柊', text: '俊基ーー！', isRight: true },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 0, speaker: '椎名', text: '・・・わかりました。それではテストをさせて下さい', isRight: false },
            { bg: 'hospital.png', character: 'igari02.png', spriteIndex: 9, speaker: '猪狩', text: 'テスト？', isRight: true },
            { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 0, speaker: '椎名', text: 'ここは人目が多い。移動しましょう', isRight: false }
        ],
        pre_stg: [
            { bg: 'sanrin.png', place: 'Sanrin', time: '2025.05', character: 'shiina.png', spriteIndex: 0, speaker: '椎名', text: '・・・ここならいいか', delay: 60, isRight: false, bgm: 'relax' },
            { bg: 'sanrin.png', character: 'shiina.png', spriteIndex: 10, speaker: '椎名', text: 'ここからは奴に任せます', isRight: false },
            { bg: 'sanrin.png', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', text: '奴？', isRight: true },
            { bg: 'sanrin.png', item: 'mask.png', isRight: true },
            { bg: 'sanrin.png', character: 'hiragi01.png', spriteIndex: 15, speaker: '柊', text: 'あ・・・ああっ', isRight: true },
            { bg: 'sanrin.png', character: 'urashiina.png', spriteIndex: 2, speaker: '椎名', text: 'ったく護のやつはよぉ。いつまでも待たせやがる', isRight: false, bgm: 'dark' },
            { bg: 'sanrin.png', character: 'igari02.png', spriteIndex: 9, speaker: '猪狩', text: 'あの・・・椎名さん？', isRight: true },
            { bg: 'sanrin.png', character: 'urashiina.png', spriteIndex: 3, speaker: '椎名', text: 'ふふ・・・はははっ', isRight: false },
            { bg: 'sanrin.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: '何がテストだ！　俺が貴様らを認めるわけねぇだろうが！', isRight: false },
            { bg: 'sanrin.png', character: 'urashiina.png', spriteIndex: 2, speaker: '椎名', text: '特にそっちの魔女、ホイホイ付いてきやがって。飛んで火に入る何とやらだ', isRight: false },
            { bg: 'sanrin.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '椎名家はその多大なる能力を使うため、潜在意識と顕在意識をバイパスするらしい', isRight: true },
            { bg: 'sanrin.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: 'つまり性格変わっちゃうわけね', isRight: true },
            { bg: 'sanrin.png', character: 'hiragi01.png', spriteIndex: 11, speaker: '柊', text: '話も通じない化け物なんだよ、あいつらは！', isRight: true },
            { bg: 'sanrin.png', character: 'urashiina.png', spriteIndex: 3, speaker: '椎名', text: '久々に外に出られて気分がいいぜ！', isRight: false },
            { bg: 'sanrin.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: '誰でもいいからぶん殴りてぇ！', isRight: false },
            { bg: 'sanrin.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: 'なんとかなんないのか', isRight: true },
            { bg: 'sanrin.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: 'まあ、叩き伏せて椎名くんを呼び戻す他ないな', isRight: true },
            { bg: 'sanrin.png', character: 'hiragi01.png', spriteIndex: 11, speaker: '柊', text: '来るよ!', isRight: true }
        ],
        event_adv: [
            { bg: 'bluesky.png', character: 'urashiina.png', spriteIndex: 2, speaker: '椎名', text: 'まさかここまで抵抗するとはな', isRight: false },
            { bg: 'bluesky.png', character: 'urashiina.png', spriteIndex: 0, speaker: '椎名', text: '俺も本気で対応しよう', isRight: false }
        ],
        post_stg: [
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: 'はぁ、はぁ・・・大丈夫かい、君たち？', isRight: false, bgm: 'relax' },
            { bg: 'yakerin.png', character: 'igari02.png', spriteIndex: 9, speaker: '猪狩', text: '戻った・・・のか？', isRight: true },
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 1, speaker: '椎名', text: '一時的に主導権を取り戻したよ。そして・・・', isRight: false },
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 2, speaker: '椎名', text: '認めてやるぜ。お前らと共に戦ってやる', isRight: false },
            { bg: 'yakerin.png', character: 'hiragi01.png', spriteIndex: 11, speaker: '柊', text: '嬉しくない', isRight: true },
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 0, speaker: '椎名', text: '僕だって納得はしてない。でも僕もこいつも死にたくない', isRight: false },
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 1, speaker: '椎名', text: 'そしてこいつは君たちの力を認めた', isRight: false },
            { bg: 'yakerin.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'やれやれ。共同戦線を張るってことでいいかな', isRight: true },
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 0, speaker: '椎名', text: '目的を果たすまではね', isRight: false },
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 3, speaker: '椎名', text: '終わったらぶっ潰してやんぞゴルァ', isRight: false },
            { bg: 'yakerin.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: '情緒どうなってんのよ', isRight: true },
            { bg: 'yakerin.png', item: 'phone2.png', text: '', se: 'vibration.mp3', isRight: false },
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 2, speaker: '椎名', text: 'はい、椎名・・・ああ、分かった', isRight: false },
            { bg: 'yakerin.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: 'どうした？', isRight: true },
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 0, speaker: '椎名', text: '僕を１年後に殺そうとしている首謀者が分かった', isRight: false },
            { bg: 'yakerin.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: 'これからそいつを潰しに行く', isRight: false },
            { bg: 'yakerin.png', character: 'hiragi01.png', spriteIndex: 1, speaker: '柊', text: 'そ。頑張ってねー', isRight: true },
            { bg: 'yakerin.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: '何言ってるんだ。君らも行くんだぞ', isRight: true },
            { bg: 'yakerin.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: 'なんでよ！', isRight: true },
            { bg: 'yakerin.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '椎名くんがやられたら君の死亡も確定事項になる', isRight: true },
            { bg: 'yakerin.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: 'バタフライエフェクトってやつだ', isRight: true },
            { bg: 'yakerin.png', character: 'hiragi01.png', spriteIndex: 11, speaker: '柊', text: 'うわ、だるっ！', isRight: true },
            { bg: 'yakerin.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '場所は？', isRight: true },
            { bg: 'yakerin.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '北極だ', isRight: true }
        ]
    },
    4: {
        stgId: 'jingu',
        adv: [
            { bg: 'advsnow.png', place: 'North Pole', time: '2025.06', character: 'igari02.png', spriteIndex: 9, speaker: '猪狩', text: 'さ、寒っ。暖風装置生成！', isRight: true, bgm: 'relax' },
            { bg: 'advsnow.png', character: 'igari02.png', spriteIndex: 13, speaker: '猪狩', text: 'あー、死ぬかと思った', isRight: true },
            { bg: 'advsnow.png', character: 'hiragi01.png', spriteIndex: 1, speaker: '柊', text: '北極だもんねぇ', isRight: true },
            { bg: 'advsnow.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: '君はそんな格好で寒くないのか？', isRight: true },
            { bg: 'advsnow.png', character: 'hiragi01.png', spriteIndex: 9, speaker: '柊', text: 'これでも私、魔女だから', isRight: true, effect: 'flashRed' },
            { bg: 'advsnow.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '周囲の温度を魔法で温めてるのか!?', isRight: true },
            { bg: 'advsnow.png', character: 'hiragi01.png', spriteIndex: 1, speaker: '柊', text: '炎の出力を弱めればいいだけだしね', isRight: true },
            { bg: 'advsnow.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '（魔法の出力を自在にコントロールするか）', isRight: true },
            { bg: 'advsnow.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '（彼女の死が世界のバランスを崩すわけだ）', isRight: true },
            { bg: 'advsnow.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: '見つけた。あいつだ', isRight: true, bgm: 'stop' },
            { bg: 'advsnow.png', character: 'jingu.png', spriteIndex: 2, speaker: '神宮寺', text: 'ここほれワンワン♪　石油がじゃんじゃん♪', isRight: false, bgm: 'dark' },
            { bg: 'advsnow.png', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', text: '・・・半袖？', isRight: true },
            { bg: 'advsnow.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: 'ZINNカンパニー代表の神宮寺恒成だな？', isRight: true },
            { bg: 'advsnow.png', character: 'jingu.png', spriteIndex: 3, speaker: '神宮寺', text: '誰だてめぇ', isRight: false },
            { bg: 'advsnow.png', character: 'jingu.png', spriteIndex: 3, speaker: 'AI', item: 'potable.png', text: '椎名護。あなたが狙うべき相手です', isRight: false },
            { bg: 'advsnow.png', character: 'jingu.png', spriteIndex: 0, speaker: '神宮寺', text: 'そうか、貴様が死をコントロールできるという血肉を持つ一族か', isRight: false },
            { bg: 'advsnow.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: '・・・なんだと？', isRight: true },
            { bg: 'advsnow.png', character: 'jingu.png', spriteIndex: 4, speaker: '神宮寺', text: '死んでもらうぞ、娘のためにな', isRight: false }
        ],
        pre_stg: [
            { bg: 'advrocket.png', character: 'kagami.png', spriteIndex: 13, speaker: '各務', text: 'な、なんだあれは！', isRight: true, bgm: 'dark' },
            { bg: 'advrocket.png', character: 'hiragi01.png', spriteIndex: 15, speaker: '柊', text: '冷蔵庫が飛んでる・・・', isRight: true },
            { bg: 'advrocket.png', character: 'jingu.png', spriteIndex: 11, speaker: '神宮寺', text: 'んはーっはっは。こんなこともあろうかと武器を用意していたのだ', isRight: false },
            { bg: 'advrocket.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '普通にミサイルで良くないか？', isRight: true },
            { bg: 'advrocket.png', character: 'jingu.png', spriteIndex: 8, speaker: '神宮寺', text: 'ちっちっちっ。これだから凡人は', isRight: false },
            { bg: 'advrocket.png', character: 'jingu.png', spriteIndex: 4, speaker: '神宮寺', text: 'AIが言ったんだよ！　家電にロケット付けたら敵を撃退できるってな！', isRight: false },
            { bg: 'advrocket.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: 'それ信じるか、普通', isRight: true },
            { bg: 'advrocket.png', character: 'jingu.png', spriteIndex: 11, speaker: '神宮寺', text: 'AIが言った事だぜ?　信じるだろ、フツーはよ！', isRight: false, effect: 'shake' },
            { bg: 'advrocket.png', character: 'urashiina.png', spriteIndex: 0, speaker: '椎名', text: '哀れな男だ。ハルシネーションを知らんらしい', isRight: true },
            { bg: 'advrocket.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '神宮寺はAIで巨万の富を得た資産家だ', isRight: true },
            { bg: 'advrocket.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '成功体験が積み重なり、盲信するに至ったのだろう', isRight: true },
            { bg: 'advrocket.png', character: 'hiragi01.png', spriteIndex: 11, speaker: '柊', text: '家電ロケット、凄い数だよ！', isRight: true },
            { bg: 'advrocket.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: 'やることは至極単純だ。奴のロケットを全部ぶち壊せばいい', isRight: true },
            { bg: 'advrocket.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: 'あの数を？　本気なの？', isRight: true },
            { bg: 'advrocket.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: 'やらなければ、君の１年後は・・・', isRight: true },
            { bg: 'advrocket.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: 'わーったわよ！　やればいいんでしょ、やれば！', isRight: true },
            { bg: 'advrocket.png', character: 'urashiina.png', spriteIndex: 3, speaker: '椎名', text: '先に行くぜ。遅れんじゃねぇぞ、お前ら！', isRight: true }
        ],
        mid_stg: [
            { bg: 'robodon.png', character: 'jingu.png', spriteIndex: 8, speaker: '神宮寺', text: 'なかなかやるな、だがこんなこともあろうかと・・・', isRight: false },
            { bg: 'robodon.png', character: 'hiragi01.png', spriteIndex: 15, speaker: '柊', text: 'え？　なに？　家電が合体して・・・', isRight: true },
            { bg: 'robodon.png', character: 'igari02.png', spriteIndex: 9, speaker: '猪狩', text: 'ロボになったな', isRight: true },
            { bg: 'robodon.png', character: 'jingu.png', spriteIndex: 2, speaker: '神宮寺', text: 'うはははっ、どうだ！　これで貴様らは一巻の終わりだ', isRight: false },
            { bg: 'robodon.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: 'さて、どう思う？', isRight: true },
            { bg: 'robodon.png', character: 'urashiina.png', spriteIndex: 3, speaker: '椎名', text: '的がデカくて当てやすそうだ', isRight: true },
            { bg: 'robodon.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '同感だ', isRight: true }
        ],
        post_stg: [
            { bg: 'boro.png', character: 'jingu.png', spriteIndex: 9, speaker: '神宮寺', text: '俺の全資産が・・・', isRight: false, bgm: 'stop' },
            { bg: 'boro.png', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', text: 'あれに全部注ぎ込んだの？　マジ？', isRight: true, bgm: 'relax' },
            { bg: 'boro.png', character: 'jingu.png', spriteIndex: 5, speaker: '神宮寺', text: 'だってAIがよ・・・', isRight: false },
            { bg: 'boro.png', character: 'jingu.png', spriteIndex: 5,speaker: 'AI', item: 'potable.png', text: '大丈夫だ、神宮寺', isRight: false },
            { bg: 'boro.png', character: 'jingu.png', spriteIndex: 5, speaker: 'AI', item: 'potable.png', text: '石油が出れば、資産は取り戻せる', isRight: false },
            { bg: 'boro.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: 'ちょっとその端末、見て良いか？', isRight: true },
            { bg: 'boro.png', character: 'jingu.png', spriteIndex: 5, speaker: '神宮寺', text: '好きにしろよ・・・', isRight: false },
            { bg: 'boro.png', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', item: 'potable.png', text: '・・・これ、ただの受信機だぞ', isRight: true },
            { bg: 'boro.png', character: 'jingu.png', spriteIndex: 7, speaker: '神宮寺', text: 'どういうことだ？', isRight: false },
            { bg: 'boro.png', character: 'igari02.png', spriteIndex: 9, speaker: '猪狩', text: 'つまりお前はAIではなく、誰かと通信していただけってことだ', isRight: true },
            { bg: 'boro.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: 'えっ!?　誰と？', isRight: true },
            { bg: 'boro.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: '決まってる。黒幕だ', isRight: true, bgm: 'stop' },
            { bg: 'boro.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: 'システムを組み替えて逆探知させよう', isRight: true },
            { bg: 'boro.png', item: 'potable2.png', text: '', isRight: true },      
            { bg: 'boro.png', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: 'ちっ、なんてこった', isRight: true, bgm: 'dark' },
            { bg: 'boro.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: 'どこだ？　地球のどこにいようと追い詰めてやる', isRight: true },
            { bg: 'boro.png', character: 'urashiina.png', spriteIndex: 1, speaker: '椎名', text: 'ん？　なんだ、上？', isRight: true },
            { bg: 'boro.png', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', text: '・・・月だ', isRight: true },
            { bg: 'boro.png', character: 'igari02.png', spriteIndex: 4, speaker: '猪狩', text: 'AIを装い、神宮寺を操った首謀者は、月にいる', isRight: true, effect: 'shake' }
        ]
    },
    5: {
        stgId: 'godai',
        adv: [
            { bg: 'univ.png', place: 'Moon', time: '2025.07', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '驚いたな。シャトルまで作れるのか君は', delay: 60, isRight: true, bgm: 'relax' },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 3, speaker: '猪狩', text: '昔、親父に叩き込まれてね', isRight: true },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '大抵の機械に関してはそらで図面引けるよ', isRight: true },
            { bg: 'univ.png', character: 'hiragi01.png', spriteIndex: 4, speaker: '柊', text: 'ぜ、全然カッコよくなんてないんだからね', isRight: true },
            { bg: 'univ.png', character: 'shiina.png', spriteIndex: 0, speaker: '椎名', text: '何、その唐突なツンデレ', isRight: false },
            { bg: 'univ.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: 'オトコはマンネリが一番ダメなのよ', isRight: true },
            { bg: 'univ.png', character: 'shiina.png', spriteIndex: 10, speaker: '椎名', text: '気分が変調しすぎる相手も疲れると思うけど', isRight: false },
            { bg: 'univ.png', character: 'hiragi01.png', spriteIndex: 15, speaker: '柊', text: '何ですって!?', isRight: true },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: 'しかし、月の裏側か', isRight: true },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 10, speaker: '猪狩', text: '石、持って帰ってもいいかな', isRight: true },
            { bg: 'univ.png', character: 'shiina.png', spriteIndex: 1, speaker: '椎名', text: '確かに。僕も一つ拾っていこうかな', isRight: false },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 2, speaker: '猪狩', text: 'わかる？　やっぱ男子たるものそうだよな！', isRight: true },
            { bg: 'univ.png', character: 'hiragi01.png', spriteIndex: 11, speaker: '柊', text: 'ライバル出現!?', isRight: true },
            { bg: 'univ.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: '違うと思うぞ', isRight: true },
            { bg: 'univ.png', effect: 'shake', text: '', bgm: 'stop' },
            { bg: 'univ.png', character: 'hiragi01.png', spriteIndex: 15, speaker: '柊', text: 'な、なに!?', isRight: true, effect: 'flashRed' }
        ],
        pre_stg: [
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: 'レーダーに反応。これは・・・戦闘機!?', isRight: true, bgm: 'dark' },
            { bg: 'univ.png', character: 'shiina.png', spriteIndex: 9, speaker: '椎名', text: '現代の科学技術で宇宙空間を飛ぶ戦闘機なんて・・・', isRight: false },
            { bg: 'univ.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '当然だろう。君らが相手しているのは、科学文明軍', isRight: true },
            { bg: 'univ.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '異世界移動が出来るほどの技術力がある奴らだぞ', isRight: true },
            { bg: 'univ.png', speaker: '？？？', text: '警告する', isRight: false },
            { bg: 'univ.png', speaker: '？？？', text: 'それ以上近づけば、我々は諸君らを撃墜する', isRight: false },
            { bg: 'univ.png', character: 'hiragi01.png', spriteIndex: 5, speaker: '柊', text: '意外に紳士的ね', isRight: true },
            { bg: 'univ.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: '１年後、私の飛行機を爆破するときも予告してきたのかな', isRight: true },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: 'いや、あの時は突然だった', isRight: true },
            { bg: 'univ.png', character: 'shiina.png', spriteIndex: 0, speaker: '椎名', text: '彼らも一枚岩ではないのかもしれない', isRight: false },
            { bg: 'univ.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'いずれにせよ、ここを突破しなければ月には着かないぞ', isRight: true },
            { bg: 'univ.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '引き返すか？', isRight: true },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: 'んなわきゃあるかよ！　イグニッション！', isRight: true },
            { bg: 'univ.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: 'シャトルに砲台が付いた!?', isRight: true },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '何としても辿り着くぞ、月に', isRight: true }
        ],
        mid_stg: [
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 11, speaker: '猪狩', text: '・・・通信？', isRight: true },
            { bg: 'univ.png', character: 'godaimo.png', spriteIndex: 0, speaker: 'G・O・D・A・I', text: '警告したはずだが？', isRight: false },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: '悪いが、こちらも退けない理由があってね', isRight: true },
            { bg: 'univ.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '君たちは科学文明軍で間違いないか', isRight: true },
            { bg: 'univ.png', character: 'godaimo.png', spriteIndex: 0, speaker: 'G・O・D・A・I', text: '我々を知るか', isRight: false },
            { bg: 'univ.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '異世界保険組合だ。聞いたことくらいはあるだろ', isRight: true },
            { bg: 'univ.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '１年後、君らがやろうとしてる計画、止めることは出来ないか', isRight: true },
            { bg: 'univ.png', character: 'godaimo.png', spriteIndex: 0, speaker: 'G・O・D・A・I', text: '・・・それは、無理だ', isRight: false },
            { bg: 'univ.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: '分かってると思うが、それは', isRight: true },
            { bg: 'univ.png', character: 'godaimo.png', spriteIndex: 0, speaker: 'G・O・D・A・I', text: '異世界条項47に抵触するのだろう？', isRight: false },
            { bg: 'univ.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: '知ってて・・・!?', isRight: true },
            { bg: 'univ.png', character: 'godaimo.png', spriteIndex: 0, speaker: 'G・O・D・A・I', text: '御婦人、この世には', isRight: false },
            { bg: 'univ.png', character: 'godaimo.png', spriteIndex: 1, speaker: 'G・O・D・A・I', text: '自身でハンドルを握ることが出来ない者がいるのだ', isRight: false },
            { bg: 'univ.png', character: 'shiina.png', spriteIndex: 0, speaker: '椎名', text: 'つまり、君のボスが諸悪の根源ってことか', isRight: true },
            { bg: 'univ.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '退く気がないのなら倒さざるを得ない', isRight: true },
            { bg: 'univ.png', character: 'godaimo.png', spriteIndex: 0, speaker: 'G・O・D・A・I', text: '承知の上だ。私はGODAI', isRight: false },
            { bg: 'univ.png', character: 'godaimo.png', spriteIndex: 1, speaker: 'G・O・D・A・I', text: '科学文明軍の最高戦力だ', isRight: false, effect: 'shake' }
        ],
        post_stg: [
            { bg: 'postuniv.png', character: 'godai.png', spriteIndex: 4, speaker: 'G・O・D・A・I', text: '強い・・・お前達の、勝ちだ', delay: 60, isRight: false, bgm: 'stop' },
            { bg: 'postuniv.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '・・・何故、手を抜いた？', isRight: true, bgm: 'relax' },
            { bg: 'postuniv.png', character: 'godai.png', spriteIndex: 4, speaker: 'G・O・D・A・I', text: '否定する。私に加減という概念はない', isRight: false },
            { bg: 'postuniv.png', character: 'igari02.png', spriteIndex: 3, speaker: '猪狩', text: '月に設置された、巨大砲台', isRight: true },
            { bg: 'postuniv.png', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: 'あれを撃たれていたら俺達は全滅していた', isRight: true },
            { bg: 'postuniv.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: '君こそ、気づいてたのに黙ってたのか!?', isRight: true },
            { bg: 'postuniv.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: '気付いたのが月に近づいてからだったんだ', isRight: true },
            { bg: 'postuniv.png', character: 'godai.png', spriteIndex: 4, speaker: 'G・O・D・A・I', text: 'エネルギー充填が不十分だっただけだ。諸君の勘違いだろう', isRight: false },
            { bg: 'postuniv.png', character: 'hiragi01.png', spriteIndex: 0, speaker: '柊', text: '俊基、どうするの', isRight: true },
            { bg: 'postuniv.png', character: 'godai.png', spriteIndex: 4, speaker: 'G・O・D・A・I', text: '私を破壊しなければ自爆プログラムが働く', isRight: false },
            { bg: 'postuniv.png', character: 'godai.png', spriteIndex: 4, speaker: 'G・O・D・A・I', text: '月もろとも破壊するだろう', isRight: false },
            { bg: 'postuniv.png', character: 'urashiina.png', spriteIndex: 2, speaker: '椎名', text: '猪狩、もたもたすんじゃねぇ', isRight: true, bgm: 'dark' },
            { bg: 'postuniv.png', character: 'urashiina.png', spriteIndex: 4, speaker: '椎名', text: 'こいつ自身が幕を引けって言ってんだ', isRight: true },
            { bg: 'postuniv.png', character: 'igari02.png', spriteIndex: 5, speaker: '猪狩', text: '・・・分かった', isRight: true },
            { bg: 'postuniv.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '分解！', isRight: true, effect: 'whiteout' },
            { bg: 'postuniv.png', character: 'godai.png', spriteIndex: 4, speaker: 'G・O・D・A・I', text: 'あり・・・がとう・・・', isRight: false }
        ]
    },
    6: {
        stgId: 'final',
        adv: [
            { bg: 'uramoon.png', character: 'cap01.png', spriteIndex: 0, speaker: '？？？', text: 'まさかお前たちの方からここへ来るとはな。柊、椎名', delay: 60, isRight: false, bgm: 'dark' },
            { bg: 'uramoon.png', character: 'shiina.png', spriteIndex: 9, speaker: '椎名', text: 'お、お前は・・・！', isRight: true },
            { bg: 'uramoon.png', character: 'hiragi01.png', spriteIndex: 15, speaker: '柊', text: 'まさか・・・！', isRight: true },
            { bg: 'uramoon.png', character: 'shiina.png', character2: 'hiragi01.png', spriteIndex: 0, spriteIndex0: 15, speaker: '椎名・柊', text: '・・・誰？', isRight: true },
            { bg: 'uramoon.png', character: 'igari02.png', spriteIndex: 4, speaker: '猪狩', text: '知らねぇのかよ！', isRight: true },
            { bg: 'uramoon.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '知るはずがないさ', isRight: true },
            { bg: 'uramoon.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '君らとは死ぬまで顔を合わせる予定は無かったのだからな', isRight: true },
            { bg: 'uramoon.png', character: 'cap01.png', spriteIndex: 5, speaker: '？？？', text: '我々の計画を!?　まさか貴様、保険組合か！', isRight: false },
            { bg: 'uramoon.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'わかってるなら話が早い', isRight: true },
            { bg: 'uramoon.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '貴様が犯そうとしてる犯罪、止める気は――', isRight: true },
            { bg: 'uramoon.png', character: 'cap01.png', spriteIndex: 3, speaker: '？？？', text: 'あると思うかね？', isRight: false },
            { bg: 'uramoon.png', character: 'hiragi01.png', spriteIndex: 1, speaker: '柊', text: 'ある！', isRight: true },
            { bg: 'uramoon.png', character: 'igari02.png', spriteIndex: 10, speaker: '猪狩', text: 'まあまあある！', isRight: true },
            { bg: 'uramoon.png', character: 'shiina.png', spriteIndex: 12, speaker: '椎名', text: 'どちらかと言えばある！', isRight: true },
            { bg: 'uramoon.png', character: 'cap01.png', spriteIndex: 7, speaker: '？？？', text: 'ないわ！　ボケどもが！', isRight: false, effect: 'shake' },
            { bg: 'uramoon.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: '怒られたわ・・・', isRight: true },
            { bg: 'uramoon.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: '君たちね・・・', isRight: true },
            { bg: 'uramoon.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: 'やることは変わらない。叩き潰せばいいんだろ？', isRight: true },
            { bg: 'uramoon.png', character: 'urashiina.png', spriteIndex: 3, speaker: '椎名', text: '基地を元のクレーターに戻してやんぞゴルァ！', isRight: true },
            { bg: 'uramoon.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '頼もしいと言うべきか', isRight: true },
            { bg: 'uramoon.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: 'だが油断はするなよ！ 突入する！', isRight: true }
        ],
        pre_stg: [
            { bg: 'base.png', character: 'igari02.png', spriteIndex: 10, speaker: '猪狩', text: 'おおっ！　SFの基地じゃねぇか！', isRight: true },
            { bg: 'base.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: '喜んでる場合じゃないよ', isRight: true },
            { bg: 'base.png', character: 'hiragi01.png', spriteIndex: 15, speaker: '柊', text: 'そこら中から戦闘機がでてきてるんだよ', isRight: true },
            { bg: 'base.png', character: 'igari02.png', spriteIndex: 3, speaker: '猪狩', text: '構やしねぇよ', isRight: true },
            { bg: 'base.png', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: '相手が科学なら俺が負ける理由はない！', isRight: true }
        ],
        mid_stg: [
            { bg: 'base.png', character: 'shiina.png', spriteIndex: 9, speaker: '椎名', text: 'あの戦艦は、さっきの・・・', isRight: true },
            { bg: 'base.png', character: 'hiragi01.png', spriteIndex: 14, speaker: '柊', text: '俊基、やっつけたはずだよね？', isRight: true },
            { bg: 'base.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'どうやら量産型が同じ戦艦を操ってるようだな', isRight: true },
            { bg: 'base.png', character: 'godaimo.png', spriteIndex: 0, speaker: '量産型GODAI', text: 'ガガガ・・・敵、殲滅する', isRight: false },
            { bg: 'base.png', character: 'igari02.png', spriteIndex: 3, speaker: '猪狩', text: '量産型なら、敵じゃねぇ', isRight: true },
            { bg: 'base.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: 'あいつは自分を『最高戦力』って言ったんだからな', isRight: true },
            { bg: 'base.png', character: 'shiina.png', spriteIndex: 1, speaker: '椎名', text: 'じゃあいまここにいる彼らは二番手以下ってことだね', isRight: true },
            { bg: 'base.png', character: 'urashiina.png', spriteIndex: 3, speaker: '椎名', text: '道開けろザコがぁ！', isRight: true },
            { bg: 'base.png', character: 'hiragi01.png', spriteIndex: 9, speaker: '柊', text: 'この落差、慣れないわー', isRight: true }
        ],
        mid_stg2: [
            { bg: 'inbase.png', character: 'cap.png', spriteIndex: 6, speaker: '科学文明軍隊長', text: 'なっ、まさかここまで来たのか!?', isRight: false },
            { bg: 'inbase.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: '悪役のテンプレ台詞すぎるだろ', isRight: true },
            { bg: 'inbase.png', character: 'shiina.png', spriteIndex: 10, speaker: '椎名', text: '人間慌てるとあんなものさ', isRight: true },
            { bg: 'inbase.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '気を抜くな。あそこに見えているあれは', isRight: true },
            { bg: 'inbase.png', character: 'cap.png', spriteIndex: 3, speaker: '科学文明軍隊長', text: '貴様の父親が開発に関わった兵器、アームコア3000だ', isRight: false },
            { bg: 'inbase.png', character: 'igari02.png', spriteIndex: 13, speaker: '猪狩', text: '全方位に主砲が付いてんじゃねえか', isRight: true },
            { bg: 'inbase.png', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: 'あのクソ親父、デタラメな兵器作りやがって', isRight: true },
            { bg: 'inbase.png', character: 'urashiina.png', spriteIndex: 3, speaker: '椎名', text: '潰し甲斐がありそうな兵器だな', isRight: true },
            { bg: 'inbase.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: 'だが、あんな兵器に近づけるのか？', isRight: true },
            { bg: 'inbase.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: '壊す前に穴だらけになっちゃうよ', isRight: true },
            { bg: 'inbase.png', character: 'cap.png', spriteIndex: 3, speaker: '科学文明軍隊長', text: 'ククク・・・貴様らもここまでだ', isRight: false },
            { bg: 'inbase.png', character: 'cap.png', spriteIndex: 1, speaker: '科学文明軍隊長', text: '宇宙の藻屑となるがいい', isRight: false },
            { bg: 'inbase.png', character: 'igari02.png', spriteIndex: 7, speaker: '猪狩', text: 'うるせぇな！　テンプレな台詞ばっかりいいやがって！', isRight: true },
            { bg: 'inbase.png', character: 'igari02.png', spriteIndex: 4, speaker: '猪狩', text: 'お前みたいな奴にやられてたまるかよ！', isRight: true }
        ],
        post_stg: [
            { bg: 'brokenbase.png', character: 'cap.png', spriteIndex: 6, speaker: '科学文明軍隊長', text: 'ば、馬鹿なぁ！　我が軍の最終兵器がぁーー！', isRight: false, effect: 'shake' },
            { bg: 'brokenbase.png', character: 'igari02.png', spriteIndex: 5, speaker: '猪狩', text: '最後まで冗談か本気かわかんない奴だな', isRight: true },
            { bg: 'brokenbase.png', character: 'kagami.png', spriteIndex: 13, speaker: '各務', text: '科学文明軍隊長、ジョン・サクラダ', isRight: true },
            { bg: 'brokenbase.png', character: 'kagami.png', spriteIndex: 12, speaker: '各務', text: '異世界条項47条違反の罪で逮捕する', isRight: true },
            { bg: 'brokenbase.png', character: 'cap.png', spriteIndex: 3, speaker: 'ジョン・サクラダ', text: 'これで終わったと思うなよ！', isRight: false },
            { bg: 'brokenbase.png', character: 'cap.png', spriteIndex: 7, speaker: 'ジョン・サクラダ', text: '我々が敗れても、いずれ次の刺客がっ・・・', isRight: false },
            { bg: 'brokenbase.png', character: 'shiina.png', spriteIndex: 10, speaker: '椎名', text: 'ここまでテンプレを極めると逆に尊敬するね', isRight: true },
            { bg: 'brokenbase.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: '１年後の私がこんなのにやられたと思うと腹立つわ', isRight: true },
            { bg: 'brokenbase.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '私はこいつを連行するのでここで失礼する', isRight: true },
            { bg: 'brokenbase.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '猪狩くん。今更だが、巻き込んで済まなかった', isRight: true },
            { bg: 'brokenbase.png', character: 'igari02.png', spriteIndex: 3, speaker: '猪狩', text: 'まあ、他人事ってわけでもないからな', isRight: true },
            { bg: 'brokenbase.png', character: 'hiragi01.png', spriteIndex: 6, speaker: '柊', text: 'なにそれ！　遠回しなプロポーズ!?', isRight: true },
            { bg: 'brokenbase.png', character: 'kagami.png', spriteIndex: 1, speaker: '各務', text: '君たちの未来が明るいものであるよう、祈らせてもらうよ', isRight: true },
            { bg: 'brokenbase.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: 'そして、できればもう会わずに済むことを願う', isRight: true },
            { bg: 'brokenbase.png', character: 'igari02.png', spriteIndex: 0, speaker: '猪狩', text: '親父にも伝えとくよ。保険組合に迷惑かけんなって', isRight: true },
            { bg: 'brokenbase.png', character: 'hiragi01.png', spriteIndex: 6, speaker: '柊', text: 'ねえ、どうなの？　ねえ俊基！', isRight: true },
            { bg: 'brokenbase.png', character: 'shiina.png', spriteIndex: 10, speaker: '椎名', text: 'しつこい女は嫌われるよ', isRight: true },
            { bg: 'brokenbase.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: 'うるさいのよアンタは！', isRight: true, effect: 'shake' }
        ],
        ending: [
            { bg: 'airport.png', speaker: '', text: '１年後', isRight: true },
            { bg: 'airport.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: '本当に本当に大丈夫なんだろうな', isRight: true },
            { bg: 'airport.png', character: 'hiragi01.png', spriteIndex: 0, speaker: '柊', text: '大丈夫だって。防護結界も３重に張ってるし' },
            { bg: 'airport.png', character: 'hiragi01.png', spriteIndex: 1, speaker: '柊', text: '核爆弾が落ちても無事だよ', isRight: true },
            { bg: 'airport.png', character: 'igari02.png', spriteIndex: 12, speaker: '猪狩', text: 'その場合俺が無事で済まないから困るが', isRight: true },
            { bg: 'airport.png', character: 'hiragi01.png', spriteIndex: 9, speaker: '柊', text: 'それより心配なのはあっちに着いてからかな'},
            { bg: 'airport.png', character: 'hiragi01.png', spriteIndex: 2, speaker: '柊', text: 'なんで大魔女様の元で修行なのよ'},
            { bg: 'airport.png', character: 'hiragi01.png', spriteIndex: 5, speaker: '柊', text: '他にも有能な魔女いるでしょーよ'},
            { bg: 'airport.png', character: 'igari02.png', spriteIndex: 10, speaker: '猪狩', text: '期待されてんじゃねぇの？', isRight: true },
            { bg: 'airport.png', character: 'hiragi01.png', spriteIndex: 0, speaker: '柊', text: 'だといいけどね'},
            { bg: 'airport.png', character: 'hiragi01.png', spriteIndex: 10, speaker: '柊', text: 'じゃ、行ってくるー'},
            { bg: 'airport.png', place: 'Airport', time: '2026.04', character: 'hiragi01.png', spriteIndex: 10, effect: 'slideOutLeft', text: '' },
            { bg: 'airport.png', character: 'igari02.png', spriteIndex: 1, speaker: '猪狩', text: 'ああ、行ってらっしゃい', isRight: true },
            { bg: 'airport02.png', speaker: '猪狩', text: '千華を乗せた飛行機はあっけなく離陸した', isRight: true },
            { bg: 'airport02.png', speaker: '猪狩', text: '各務によれば、修正された歴史の記憶は消えていくものらしい', isRight: true },
            { bg: 'airport02.png', character: 'igari02.png', spriteIndex: 3, speaker: '猪狩', text: '月に行った記憶が無くなるのはちょっと惜しい気もするけどな', isRight: true },
            { bg: 'airport02.png', character: 'igari02.png', spriteIndex: 1, speaker: '猪狩', text: 'さて、仕事に戻るとしますか', isRight: true }
        ]
    }
};
