const VER_SCENARIO_MAMORU = "0.5.0"; // バージョン更新（ステージ3：カジノでのインベーダーゲーム戦シナリオを追加）
 
window.scenarios = window.scenarios || {};
 
// 椎名 護 ルートのシナリオデータ
scenarios.mamoru = {
    'opening': [
        { bg: 'ope.webp', place: '解剖場', time: '2026.4', character: 'shiina.webp', spriteIndex: 9, speaker: '護', text: 'こ、ここは？', delay: 60, bgm: 'dark' },
        { bg: 'ope.webp', character: 'kagejingu.webp', spriteIndex: 2, speaker: '？？？', text: 'なんだ、麻酔が切れちまったのか？' },
        { bg: 'ope.webp', character: 'kagejingu.webp', spriteIndex: 1, speaker: '？？？', text: 'まあいい、やることは変わらない' },
        { bg: 'ope.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: '何をする気だ？' },
        { bg: 'ope.webp', character: 'kagejingu.webp', spriteIndex: 11, speaker: '？？？', text: 'お前の心臓をもらうのさ' },
        { bg: 'ope.webp', character: 'kagejingu.webp', spriteIndex: 2, speaker: '？？？', text: '生きたままな' },
        { bg: 'ope.webp', character: 'shiina.webp', spriteIndex: 8, speaker: '護', text: '君は何を言ってるんだ!?' },
        { bg: 'ope.webp', character: 'kagejingu.webp', spriteIndex: 10, speaker: '？？？', text: '礼を言うよ、椎名護' },
        { bg: 'ope.webp', character: 'kagejingu.webp', spriteIndex: 1, speaker: '？？？', text: 'お前が仮面の力をうまく使えなくて助かった' },
        { bg: 'ope.webp', character: 'kagejingu.webp', spriteIndex: 10, speaker: '？？？', text: '本物の椎名一族だったらこうはいかなかった' },
        { bg: 'ope.webp', item: 'chain.webp', se: 'vibration.mp3', text: '' },
        { bg: 'ope.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: 'やめろ！' },
        { bg: 'ope.webp', character: 'kagejingu.webp', spriteIndex: 3, speaker: '？？？', text: '悪いがやめるわけにはいかない' },
        { bg: 'ope.webp', character: 'kagejingu.webp', spriteIndex: 5, speaker: '？？？', text: '死んでくれ、娘のために' },
        { bg: 'ope.webp', item: 'chain.webp', se: 'vibration.mp3', effect: 'shake', text: '' },
        { bg: 'ope.webp', character: 'shiina.webp', spriteIndex: 5, speaker: '護', text: 'やめろーーーー！', effect: 'whiteout' },
       
        // 背景を赤一色に
        { bg: 'red', text: '', delay: 60, bgm: 'stop' },
       
        { bg: 'meeting.webp', place: 'Hospital', time: '2025.04', character: 'nurse.webp', spriteIndex: 4, speaker: '看護師', text: '先生、先生？', delay: 30, bgm: 'relax' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 5, speaker: '護', text: 'やめろ！', effect: 'shake' },
        { bg: 'meeting.webp', character: 'nurse.webp', spriteIndex: 2, speaker: '看護師', text: 'えっ？　ご面会、お止めしますか？' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 8, speaker: '護', text: '桧山さん・・・ここは' },
        { bg: 'meeting.webp', character: 'nurse.webp', spriteIndex: 4, speaker: '桧山', text: '先生、ひょっとして居眠りしてました？' },
        { bg: 'meeting.webp', character: 'nurse.webp', spriteIndex: 5, speaker: '桧山', text: '働きすぎには注意しないと駄目ですよ' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 2, speaker: '護', text: 'はは・・・そのようだね' },
        { bg: 'meeting.webp', character: 'nurse.webp', spriteIndex: 0, speaker: '桧山', text: 'じゃあ面会の人、入れますね' },
        { bg: 'meeting.webp', character: 'nurse.webp', spriteIndex: 0, effect: 'slideOutLeft', text: '' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: '失礼する。生きながら心臓を取られた気分はどうだ？' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 9, speaker: '護', text: 'どうしてそれを!?' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: '今から１年後に君の解剖記録を読んだからな' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 7, speaker: '護', text: '・・・１年後？' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: 'カレンダーを見るといい' },
        { bg: 'meeting.webp', item: 'calendar.webp', text: '' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 9, speaker: '護', text: '2025年・・・4月3日だって!?　そんなバカな！' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: '１年後の今日、君は臓器目的の男に捉えられ、殺された' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: 'だが我々にとって、それは都合が悪くてね' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 8, speaker: '護', text: '我々？　あなたは一体' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: '異世界保険組合。散らばる世界の均衡を保つ仕事だ' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 10, speaker: '護', text: '異世界保険組合・・・なるほど' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 6, speaker: '各務', text: '驚かないのだな' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '護', text: '実家が特殊ですから、非日常には慣れてるんです' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '護', text: 'それで、あなたは何のために僕のところへ？' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: '単刀直入に言う。君に椎名家を継いでほしい' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 7, speaker: '護', text: 'あなた、椎名の回し者ですか？' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 3, speaker: '護', text: '僕に幻覚をみせ、家を継がせようと？' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: '信じる信じないは勝手だがね' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: 'このまま１年後を迎えれば、死は確実に訪れるぞ' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: 'はあ・・・参ったな' },
        { bg: 'meeting.webp', character: 'kagami.webp', spriteIndex: 2, speaker: '各務', text: 'どうした？' },
        { bg: 'meeting.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: '家督は既に弟に譲ってしまったんですよ' },
        { bg: 'meeting.webp', effect: 'whiteout', text: '' }
    ],
    'kagami_arrival': [
        { bg: 'shiinake.webp', place: 'Shiina House', time: '2025.04', character: 'eiji.webp', spriteIndex: 3, speaker: '衛二', text: '家督を譲れ？', delay: 60, bgm: 'dark' },
        { bg: 'shiinake.webp', character: 'eiji.webp', spriteIndex: 4, speaker: '衛二', text: '椎名の家業には興味ないって言ってたじゃないか！' },
        { bg: 'shiinake.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: '仕方ないんだよ、事情が事情で' },
        { bg: 'shiinake.webp', character: 'eiji.webp', spriteIndex: 2, speaker: '衛二', text: 'それでも納得できないね！' },
        { bg: 'shiinake.webp', character: 'eiji.webp', spriteIndex: 8, speaker: '衛二', text: '親父も言ってやれよ！' },
        { bg: 'shiinake.webp', character: 'tadashige.webp', spriteIndex: 0, speaker: '忠重', text: '衛二は厳しい修行で仮面の力を手に入れた' },
        { bg: 'shiinake.webp', character: 'tadashige.webp', spriteIndex: 1, speaker: '忠重', text: '家督を継ぎたいのであれば、衛二に勝る力を証明しろ' },
        { bg: 'shiinake.webp', character: 'eiji.webp', spriteIndex: 7, speaker: '衛二', text: '親父!?　本気かよ!?' },
        { bg: 'shiinake.webp', character: 'shiina.webp', spriteIndex: 10, speaker: '護', text: '・・・わかった' }
    ],
    1: {
        stgId: 'eiji',
        adv: [
            { bg: 'nightmt.webp', place: 'Night Mountain', time: '2025.04', character: 'eiji.webp', spriteIndex: 0, speaker: '衛二', text: '仮面は持ってんだろ？', delay: 60, bgm: 'relax' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '護', text: '一応僕も椎名の人間だからね' },
            { bg: 'nightmt.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: 'すまないが、部外者にもわかるように説明してもらってもいいかな' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 1, speaker: '忠重', text: 'まあ要は仮面の力をより示せた方の勝利、ということだ' },
            { bg: 'nightmt.webp', character: 'eiji.webp', spriteIndex: 3, speaker: '衛二', text: 'そもそも仮面の力、使えんのかよ？　医者なんて仕事に逃げた兄貴がさ' }
        ],
        pre_stg: [
            { bg: 'nightmt.webp', item: 'mask.webp', se: 'vibration.mp3', text: '', bgm: 'stop' },
            { bg: 'nightmt.webp', character: 'urashiina.webp', spriteIndex: 2, speaker: '護(裏)', text: '・・・これでいいか？', bgm: 'dark' },
            { bg: 'nightmt.webp', item: 'mask2.webp', se: 'vibration.mp3', text: '' },
            { bg: 'nightmt.webp', character: 'uraeiji.webp', spriteIndex: 3, speaker: '衛二(裏)', text: 'はっ、一応使えはすんのかよ' },
            { bg: 'nightmt.webp', character: 'urashiina.webp', spriteIndex: 0, speaker: '護(裏)', text: '悪いが負けるつもりはないぞ', bgm: 'dark' },
            { bg: 'nightmt.webp', character: 'uraeiji.webp', spriteIndex: 1, speaker: '衛二(裏)', text: 'その程度の力で？ 笑わせんな' },
            { bg: 'nightmt.webp', character: 'uraeiji.webp', spriteIndex: 2, speaker: '衛二(裏)', text: '家督を継いだ俺の力、見せてやるよ', effect: 'shake' }
        ],
        post_stg: [
            { bg: 'nightmt.webp', character: 'uraeiji.webp', spriteIndex: 4, speaker: '衛二(裏)', text: '何でだよ・・・何で勝てねぇんだよ！', bgm: 'stop', effect: 'shake' },
            { bg: 'nightmt.webp', character: 'eiji.webp', spriteIndex: 8, speaker: '衛二', text: '勉強だって運動だって、いつだって兄貴は一番だった', bgm: 'relax' },
            { bg: 'nightmt.webp', character: 'eiji.webp', spriteIndex: 8, speaker: '衛二', text: 'だから俺、必死で仮面の力を・・・' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: '衛二・・・' },
            { bg: 'nightmt.webp', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: '衛二くん、椎名くんは１年後に殺される運命を覆すために' },
            { bg: 'nightmt.webp', character: 'eiji.webp', spriteIndex: 9, speaker: '衛二', text: 'わかってるよ。俺だって兄貴に死んでもらいたくはない' },
            { bg: 'nightmt.webp', character: 'eiji.webp', spriteIndex: 0, speaker: '衛二', text: 'ただ、納得したかっただけだ' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 1, speaker: '忠重', text: '勝負はついた。両者とも見事だったぞ' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 0, speaker: '忠重', text: '家督は護に譲るものとする' },
            { bg: 'nightmt.webp', effect: 'whiteout', text: '' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 9, speaker: '護', text: 'これは・・・力が溢れてくる' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 0, speaker: '忠重', text: '先祖の力がお前の仮面に注がれたのだ' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 0, speaker: '忠重', text: '今後、椎名家の依頼はお前が指揮をとれ' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '護', text: 'わかった。でも、医者は続けたい。いいかな' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 1, speaker: '忠重', text: '好きにしろ、お前が当主だ' },
            { bg: 'nightmt.webp', character: 'eiji.webp', spriteIndex: 6, speaker: '衛二', text: '兄貴、大変だ！　UFOが攻めてきたって報告が！', effect: 'shake', bgm: 'dark' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 2, speaker: '忠重', text: 'ほっ、早速だな' },
            { bg: 'nightmt.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: 'UFOと戦ったことが？' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 2, speaker: '忠重', text: '日常茶飯時だ。我々にとって外来種駆除の様なものよ' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 0, speaker: '忠重', text: '護、当主としての初仕事だ。UFOを全滅させろ' },
            { bg: 'nightmt.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: '就任早々慌ただしいな' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '護', text: '大丈夫です。忙しいのには慣れてますから' }
        ],
        loss_adv: [ 
            { bg: 'nightmt.webp', character: 'uraeiji.webp', spriteIndex: 2, speaker: '衛二(裏)', text: 'ははははっ！　勝った！　兄貴に勝った！', effect: 'shake', bgm: 'stop' },
            { bg: 'nightmt.webp', character: 'kagami.webp', spriteIndex: 6, speaker: '各務', text: '椎名くん、残念だが君の運命は確定してしまった', bgm: 'dark' },
            { bg: 'nightmt.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: 'もはや何度時間を巻き戻しても無駄だろう' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: 'そんな・・・' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 1, speaker: '忠重', text: '護よ・・・落ち込むでない' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: '放っといてくれよ、父さん。僕はもう死ぬんだ' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 0, speaker: '忠重', text: '次回はもっとボムを使え' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 8, speaker: '護', text: 'え、なに？　ボム・・・？' },
            { bg: 'nightmt.webp', character: 'tadashige.webp', spriteIndex: 0, speaker: '忠重', text: '画面上部でボムを使い続けるのだ。そうすれば衛二に勝てる' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 8, speaker: '護', text: 'ちょっと待ってよ、ボムって何のこと・・・' },
            { bg: 'nightmt.webp', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: '気にするな。こことはまた別の世界の話さ' },
            { bg: 'nightmt.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: '・・・' }
        ]
    },
    2: {
        stgId: 'kagami',
        adv: [
            { bg: 'citypanic.webp', character: 'shiina.webp', spriteIndex: 12, speaker: '護', text: '確かにUFOが大量に現れてるね', delay: 60, bgm: 'dark' },
            { bg: 'citypanic.webp', character: 'kagami.webp', spriteIndex: 7, speaker: '各務', text: '・・・あれは!!'},
            { bg: 'citypanic.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '護', text: '各務さん？' },
            { bg: 'citypanic.webp', character: 'kagami.webp', spriteIndex: 10, speaker: '各務', text: 'うん・・・非常にその・・・申し訳ないんだが' },
            { bg: 'citypanic.webp', character: 'kagami.webp', spriteIndex: 2, speaker: '各務', text: 'あれはうちの迎撃装置だ' },
            { bg: 'citypanic.webp', character: 'shiina.webp', spriteIndex: 9, speaker: '護', text: 'ええ！？', effect: 'shake' },
            { bg: 'citypanic.webp', character: 'kagami.webp', spriteIndex: 2, speaker: '各務', text: '別件で使ったあと、スイッチを切るのを忘れてしまったようだ' },
            { bg: 'citypanic.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '護', text: 'よかった。じゃあ各務さんにお任せすれば・・・' },
            { bg: 'citypanic.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: 'スイッチはな、母艦の中にあるんだ' },
            { bg: 'citypanic.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: '母艦・・・無数の戦闘機に守られてますね' },
            { bg: 'citypanic.webp', character: 'tadashige.webp', spriteIndex: 2, speaker: '忠重', text: '丁度いいじゃないか、護' },
            { bg: 'citypanic.webp', character: 'tadashige.webp', spriteIndex: 1, speaker: '忠重', text: '先祖の力を引き継いだお前の力、試してみろ' },
            { bg: 'citypanic.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: 'いくら何でも多勢に無勢だよ' },
            { bg: 'citypanic.webp', character: 'tadashige.webp', spriteIndex: 4, speaker: '忠重', text: '家督、衛二に戻してもいいんだぞ' },
            { bg: 'citypanic.webp', item: 'mask.webp', se: 'vibration.mp3', text: '' },
            { bg: 'citypanic.webp', character: 'urashiina.webp', spriteIndex: 3, speaker: '護(裏)', text: 'ちっ、しゃーねぇな！　行ってくらぁ', effect: 'shake' },
            { bg: 'citypanic.webp', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: '大丈夫なのか。うちのシステムはかなり堅牢だぞ' },
            { bg: 'citypanic.webp', character: 'tadashige.webp', spriteIndex: 8, speaker: '忠重', text: '心配はいらん。あいつは家を継ぐのを拒否していたがな' },
            { bg: 'citypanic.webp', character: 'tadashige.webp', spriteIndex: 1, speaker: '忠重', text: '才能は、一族随一だ' }
        ],
        pre_stg: [
            { bg: 'citypanic.webp',character: 'urashiina.webp', spriteIndex: 3, speaker: '護(裏)', text: '的が・・・的が一杯だ！　うははははっ！', effect: 'shake' },
            { bg: 'citypanic.webp',character: 'kagami.webp', spriteIndex: 6, speaker: '各務', text: '椎名くん・・・なんか随分とハイだな' },
            { bg: 'citypanic.webp',character: 'tadashige.webp', spriteIndex: 8, speaker: '忠重', text: '仮面は脳を100％使用すると言われてる' },
            { bg: 'citypanic.webp',character: 'tadashige.webp', spriteIndex: 0, speaker: '忠重', text: '理性も本能も全部剥き出しになるというわけだ' },
            { bg: 'citypanic.webp',character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: '椎名くんは普段、色々我慢してるんだな' },
            { bg: 'citypanic.webp',character: 'urashiina.webp', spriteIndex: 3, speaker: '護(裏)', text: 'ぶっ潰すぞオラァ！', effect: 'shake' },
            { bg: 'citypanic.webp',character: 'tadashige.webp', spriteIndex: 8, speaker: '忠重', text: 'あいつ、怒らせんように気をつけよう・・・' }
        ],
        event_adv: [
            { bg: 'cityboss.webp', character: 'urashiina.webp', spriteIndex: 0, speaker: '護(裏)', text: 'ほう、なかなかデケェじゃねぇか' },
            { bg: 'cityboss.webp', character: 'kagami.webp', spriteIndex: 13, speaker: '各務', text: '母艦の弾幕は半端ないぞ、椎名くん' },
            { bg: 'cityboss.webp', character: 'urashiina.webp', spriteIndex: 3, speaker: '護(裏)', text: '弾幕？　見えねぇな、そんなモン' },
            { bg: 'cityboss.webp', character: 'urashiina.webp', spriteIndex: 2, speaker: '護(裏)', text: '真・言・展・開！', effect: 'shake' }
        ],
        post_stg: [
            { bg: 'breakufo2.webp', character: 'shiina.webp', spriteIndex: 9, speaker: '護', text: 'やった・・・のか？　僕が？', delay: 60, bgm: 'relax' },
            { bg: 'breakufo2.webp', character: 'kagami.webp', spriteIndex: 6, speaker: '各務', text: 'ああ、やり過ぎたくらいだ' },
            { bg: 'breakufo2.webp', character: 'tadashige.webp', spriteIndex: 4, speaker: '忠重', text: '護。後始末のコストも考えて動いてもらわねば困るぞ' },
            { bg: 'breakufo2.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '護', text: 'ご、ごめんなさい、父さん', effect: 'shake' },
            { bg: 'breakufo2.webp', character: 'tadashige.webp', spriteIndex: 8, speaker: '忠重', text: 'とはいえ、今回はよしとするか' },
            { bg: 'breakufo2.webp', character: 'shiina.webp', spriteIndex: 9, speaker: '護', text: 'えっ！？' },
            { bg: 'breakufo2.webp', character: 'tadashige.webp', spriteIndex: 1, speaker: '忠重', text: '世に十分知らしめただろうからな、新当主の力を' },
            { bg: 'breakufo2.webp', character: 'tadashige.webp', spriteIndex: 2, speaker: '忠重', text: 'これから忙しくなるぞ。ははははっ' },
            { bg: 'breakufo2.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: 'なんか・・・すまない' },
            { bg: 'breakufo2.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '護', text: '良いんです。僕が自分で選んだ・・・いや' },
            { bg: 'breakufo2.webp', character: 'shiina.webp', spriteIndex: 10, speaker: '護', text: '自分で『選び直した』道ですから' },
            { bg: 'breakufo2.webp', character: 'kagami.webp', spriteIndex: 1, speaker: '各務', text: '潔い男だな、君は' },
            { bg: 'breakufo2.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '護', text: 'ところで各務さん。これで僕は一年後、死なずに済むのでしょうか' },
            { bg: 'breakufo2.webp', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: 'いや。もちろん、力を得た上で元凶となる相手を倒さなくてはならない' },
            { bg: 'breakufo2.webp', character: 'shiina.webp', spriteIndex: 12, speaker: '護', text: '元凶、ですか・・・？' },
            { bg: 'breakufo2.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: 'すまない、我々も君が何者かに殺されたという情報しかないんだ' },
            { bg: 'breakufo2.webp', character: 'shiina.webp', spriteIndex: 10, speaker: '護', text: '自分で探すしかない、か' }
        ]
    },
    3: { 
        stgId: 'invader',
        adv: [
            { bg: 'casino01.webp', place: 'Casino', time: '2025.05', character: 'kagami.webp', spriteIndex: 0, speaker: '各務', text: 'カジノ？', delay: 60, bgm: 'relax' },
            { bg: 'casino01.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '椎名', text: 'うちの情報部が掴みました' },
            { bg: 'casino01.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '椎名', text: '椎名家を狙う男がここに出入りしていると' },
            { bg: 'casino01.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: '大丈夫なのか？　こういう所はその、ヤバい人たちが・・・' },
            { bg: 'casino01.webp', character: 'monban.webp', spriteIndex: 0, speaker: '門番', text: 'ご紹介は？', isRight: false },
            { bg: 'casino01.webp', character: 'kagami.webp', spriteIndex: 2, speaker: '各務', text: 'ほら、言った側から' },
            { bg: 'casino01.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '椎名', text: '僕はこういう者です' },
            { bg: 'casino01.webp', item: 'mask.webp', text: '', se: 'vibration.mp3' },
            { bg: 'casino01.webp', character: 'monban.webp', spriteIndex: 0, speaker: '門番', text: '椎名家のッ・・・失礼しました', isRight: false, effect: 'shake' },
            { bg: 'casino01.webp', character: 'kagami.webp', spriteIndex: 6, speaker: '各務', text: '凄いな' },
            { bg: 'casino01.webp', character: 'shiina.webp', spriteIndex: 10, speaker: '椎名', text: '残念ながら後ろ暗い組織には名が知れているんです' },
            
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: '噂は聞いてますよ、椎名の新当主', isRight: false, bgm: 'dark' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: '我々に何の御用で？', isRight: false },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '椎名', text: '我々を狙っている者がいると聞いている。何か知らないか' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'まあ、椎名家ですからねぇ', isRight: false },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: '狙う者は山程いるでしょうな', isRight: false },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '椎名', text: 'そうか・・・邪魔したね' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: '・・・いや、一つ思い当たる節があります', isRight: false },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '椎名', text: '思い当たる節？' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'ええ、ですがここはカジノ。私と賭けをしませんか', isRight: false },
            { bg: 'casino02.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: '駄目だ、椎名くん。相手のステージで戦っては' },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '椎名', text: '話だけは聞く。妙な賭けならお断りだ' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: '一般的なインベーダーゲームをしてもらいたいだけです', isRight: false },
            { bg: 'casino02.webp', item: 'invader.webp', text: '' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: '三面までクリアできたら勝ちでいい', isRight: false },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '椎名', text: 'わかった' },
            { bg: 'casino02.webp', character: 'kagami.webp', spriteIndex: 2, speaker: '各務', text: '待つんだ、椎名くん！　何か細工でもされてたら', effect: 'shake' },
            { bg: 'casino02.webp', item: 'invader.webp', text: '' },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '椎名', text: '構いません。僕が勝ったら情報はもらいます' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'ただし負けた場合、その仮面を頂く。構いませんかな', isRight: false },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '椎名', text: 'いいですよ' },
            { bg: 'casino02.webp', character: 'kagami.webp', spriteIndex: 2, speaker: '各務', text: '椎名くん！', effect: 'shake' }
        ],
        pre_stg: [
            { bg: 'casino02.webp', character: 'kagami.webp', spriteIndex: 9, speaker: '各務', text: '一見普通のインベーダーゲームだが', bgm: 'stop' },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 1, speaker: '椎名', text: '心配ありません。これでも昔は結構ゲームしてましたから' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'では、スタートです', isRight: false }
        ],
        event_adv: [
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 8, speaker: '椎名', text: 'あれ？　これは・・・', bgm: 'dark' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'いい忘れました', isRight: false },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'このゲームはうち用にカスタマイズされてましてな', isRight: false },
            { bg: 'casino02.webp', character: 'kagami.webp', spriteIndex: 13, speaker: '各務', text: '敵が無数に・・・これはイカサマだ！', effect: 'shake' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: '私がいつ普通のインベーダーゲームと言いましたかな？', isRight: false },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'ギャンブル仕様になってるとも説明はしませんでしたがね', isRight: false },
            { bg: 'casino02.webp', character: 'kagami.webp', spriteIndex: 2, speaker: '各務', text: 'こんな賭けは無効だ、椎名くん！', effect: 'shake' },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 10, speaker: '椎名', text: '各務さん、大丈夫ですよ' },
            { bg: 'casino02.webp', item: 'mask.webp', text: '', se: 'vibration.mp3' },
            { bg: 'casino02.webp', character: 'urashiina.webp', spriteIndex: 0, speaker: '護(裏)', text: 'どーせそんなことだろうと思ってたからなぁ' }
        ],
        post_stg: [
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'ば、バカな・・・', isRight: false, effect: 'shake', bgm: 'stop' },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 0, speaker: '椎名', text: '約束だ、情報を話してもらうぞ', bgm: 'relax' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: '・・・三日くれないか', isRight: false },
            { bg: 'casino02.webp', character: 'kagami.webp', spriteIndex: 3, speaker: '各務', text: 'おい！　椎名くんは貴様のイカサマゲームに勝ったんだぞ', effect: 'shake' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'や、約束は守る。だが私も言えば命がないんだ', isRight: false },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: '高跳びする時間をくれ。２日でいい', isRight: false },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 4, speaker: '椎名', text: '・・・わかった' },
            { bg: 'casino02.webp', character: 'kagami.webp', spriteIndex: 6, speaker: '各務', text: 'いいのか？' },
            { bg: 'casino02.webp', character: 'shiina.webp', spriteIndex: 10, speaker: '椎名', text: '我が家から逃げられるとは思えませんから' },
            { bg: 'casino02.webp', character: 'casinoboss.webp', spriteIndex: 0, speaker: 'カジノオーナー', text: 'あ、ありがとう', isRight: false }
        ]
    },
    4: { adv: [], pre_stg: [], post_stg: [] },
    5: { adv: [], pre_stg: [], post_stg: [] },
    6: { adv: [], pre_stg: [], post_stg: [] }
};
