const VER_SCENARIO_MAMORU = "0.4.0"; // バージョン更新（ステージ2：各務システムの暴走とUFO戦のシナリオを追加）

window.scenarios = window.scenarios || {};

// 椎名 護 ルートのシナリオデータ
scenarios.mamoru = {
    'opening': [
        { bg: 'ope.png', place: '解剖場', time: '1年前', character: 'shiina.png', spriteIndex: 9, speaker: '護', text: 'こ、ここは？', delay: 60, bgm: 'dark' },
        { bg: 'ope.png', character: 'kagejingu.png', spriteIndex: 2, speaker: '？？？', text: 'なんだ、麻酔が切れちまったのか？' },
        { bg: 'ope.png', character: 'kagejingu.png', spriteIndex: 1, speaker: '？？？', text: 'まあいい、やることは変わらない' },
        { bg: 'ope.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: '何をする気だ？' },
        { bg: 'ope.png', character: 'kagejingu.png', spriteIndex: 11, speaker: '？？？', text: 'お前の心臓をもらうのさ' },
        { bg: 'ope.png', character: 'kagejingu.png', spriteIndex: 2, speaker: '？？？', text: '生きたままな' },
        { bg: 'ope.png', character: 'shiina.png', spriteIndex: 8, speaker: '護', text: '君は何を言ってるんだ!?' },
        { bg: 'ope.png', character: 'kagejingu.png', spriteIndex: 10, speaker: '？？？', text: '礼を言うよ、椎名護' },
        { bg: 'ope.png', character: 'kagejingu.png', spriteIndex: 1, speaker: '？？？', text: 'お前が仮面の力をうまく使えなくて助かった' },
        { bg: 'ope.png', character: 'kagejingu.png', spriteIndex: 10, speaker: '？？？', text: '本物の椎名一族だったらこうはいかなかった' },
        { bg: 'ope.png', item: 'chain.png', se: 'vibration.mp3', text: '' },
        { bg: 'ope.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: 'やめろ！' },
        { bg: 'ope.png', character: 'kagejingu.png', spriteIndex: 3, speaker: '？？？', text: '悪いがやめるわけにはいかない' },
        { bg: 'ope.png', character: 'kagejingu.png', spriteIndex: 5, speaker: '？？？', text: '死んでくれ、娘のために' },
        { bg: 'ope.png', item: 'chain.png', se: 'vibration.mp3', effect: 'shake', text: '' },
        { bg: 'ope.png', character: 'shiina.png', spriteIndex: 5, speaker: '護', text: 'やめろーーーー！', effect: 'whiteout' },
        
        // 背景を赤一色に
        { bg: 'red', text: '', delay: 60, bgm: 'stop' },
        
        { bg: 'hospital.png', place: 'Hospital', time: '2025.04', character: 'nurse.png', spriteIndex: 4, speaker: '看護師', text: '先生、先生？', delay: 30, bgm: 'relax' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 5, speaker: '護', text: 'やめろ！', effect: 'shake' },
        { bg: 'hospital.png', character: 'nurse.png', spriteIndex: 2, speaker: '看護師', text: 'えっ？　ご面会、お止めしますか？' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 8, speaker: '護', text: '桧山さん・・・ここは' },
        { bg: 'hospital.png', character: 'nurse.png', spriteIndex: 4, speaker: '桧山', text: '先生、ひょっとして居眠りしてました？' },
        { bg: 'hospital.png', character: 'nurse.png', spriteIndex: 5, speaker: '桧山', text: '働きすぎには注意しないと駄目ですよ' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 2, speaker: '護', text: 'はは・・・そのようだね' },
        { bg: 'hospital.png', character: 'nurse.png', spriteIndex: 0, speaker: '桧山', text: 'じゃあ面会の人、入れますね' },
        { bg: 'hospital.png', character: 'nurse.png', spriteIndex: 0, effect: 'slideOutLeft', text: '' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '失礼する。生きながら心臓を取られた気分はどうだ？' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 9, speaker: '護', text: 'どうしてそれを!?' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '今から１年後に君の解剖記録を読んだからな' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 7, speaker: '護', text: '・・・１年後？' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'カレンダーを見るといい' },
        { bg: 'ope.png', item: 'calendar.png', text: '' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 9, speaker: '護', text: '2025年・・・4月2日だって!?　そんなバカな！' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '１年後の今日、君は臓器目的の男に捉えられ、殺された' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'だが我々にとって、それは都合が悪くてね' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 8, speaker: '護', text: '我々？　あなたは一体' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '異世界保険組合。散らばる世界の均衡を保つ仕事だ' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 10, speaker: '護', text: '異世界保険組合・・・なるほど' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: '驚かないのだな' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 0, speaker: '護', text: '実家が特殊ですから、非日常には慣れてるんです' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 1, speaker: '護', text: 'それで、あなたは何のために僕のところへ？' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '単刀直入に言う。君に椎名家を継いでほしい' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 7, speaker: '護', text: 'あなた、椎名の回し者ですか？' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 3, speaker: '護', text: '僕に幻覚をみせ、家を継がせようと？' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '信じる信じないは勝手だがね' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: 'このまま１年後を迎えれば、死は確実に訪れるぞ' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: 'はあ・・・参ったな' },
        { bg: 'hospital.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: 'どうした？' },
        { bg: 'hospital.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: '家督は既に弟に譲ってしまったんですよ' },
        { bg: 'hospital.png', effect: 'whiteout', text: '' }
    ],
    'kagami_arrival': [
        { bg: 'shiinake.png', place: 'Shiina House', time: '2025.04', character: 'eiji.png', spriteIndex: 3, speaker: '衛二', text: '家督を譲れ？', delay: 60, bgm: 'dark' },
        { bg: 'shiinake.png', character: 'eiji.png', spriteIndex: 4, speaker: '衛二', text: '椎名の家業には興味ないって言ってたじゃないか！' },
        { bg: 'shiinake.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: '仕方ないんだよ、事情が事情で' },
        { bg: 'shiinake.png', character: 'eiji.png', spriteIndex: 2, speaker: '衛二', text: 'それでも納得できないね！' },
        { bg: 'shiinake.png', character: 'eiji.png', spriteIndex: 8, speaker: '衛二', text: '親父、どうよ？' },
        { bg: 'shiinake.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '衛二は厳しい修行で仮面の力を手に入れた' },
        { bg: 'shiinake.png', character: 'tadashige.png', spriteIndex: 1, speaker: '忠重', text: '家督を継ぎたいのであれば、衛二に勝る力を証明しろ' },
        { bg: 'shiinake.png', character: 'shiina.png', spriteIndex: 10, speaker: '護', text: '・・・わかった' }
    ],
    1: {
        stgId: 'eiji', 
        adv: [
            { bg: 'nightmt.png', place: 'Night Mountain', time: '2025.04', character: 'eiji.png', spriteIndex: 0, speaker: '衛二', text: '仮面は持ってんだろ？', delay: 60, bgm: 'relax' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 0, speaker: '護', text: '一応僕も椎名の人間だからね' },
            { bg: 'nightmt.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'すまないが、部外者にもわかるように説明してもらってもいいかな' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 10, speaker: '護', text: 'すみません、各務さん' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 1, speaker: '護', text: 'うちの秘匿事項なのでそれはちょっと' },
            { bg: 'nightmt.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: 'そうか・・・' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: 'すまないな、異世界の客人よ' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 1, speaker: '忠重', text: 'まあ要は仮面の力をより示せた方の勝利、ということだ' },
            { bg: 'nightmt.png', character: 'eiji.png', spriteIndex: 3, speaker: '衛二', text: 'そもそも仮面の力、使えんのかよ？　医者なんて仕事に逃げた兄貴がさ' }
        ], 
        pre_stg: [
            { bg: 'nightmt.png', item: 'mask.png', se: 'vibration.mp3', text: '', bgm: 'stop' },
            { bg: 'nightmt.png', character: 'urashiina.png', spriteIndex: 2, speaker: '護(裏)', text: '・・・これでいいか？', bgm: 'dark' },
            { bg: 'nightmt.png', item: 'mask2.png', se: 'vibration.mp3', text: '' },
            { bg: 'nightmt.png', character: 'uraeiji.png', spriteIndex: 3, speaker: '衛二(裏)', text: '上等だよ、流れ弾に当たって死んでも知らねぇからな！', effect: 'shake' }
        ], 
        post_stg: [ 
            { bg: 'nightmt.png', character: 'uraeiji.png', spriteIndex: 4, speaker: '衛二(裏)', text: '何でだよ・・・何で勝てねぇんだよ！', bgm: 'stop', effect: 'shake' },
            { bg: 'nightmt.png', character: 'eiji.png', spriteIndex: 8, speaker: '衛二', text: '勉強だって運動だって、いつだって兄貴は一番だった', bgm: 'relax' },
            { bg: 'nightmt.png', character: 'eiji.png', spriteIndex: 8, speaker: '衛二', text: 'だから俺、必死で仮面の力を・・・' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: '衛二・・・' },
            { bg: 'nightmt.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '衛二くん、椎名くんは１年後に殺される運命を覆すために' },
            { bg: 'nightmt.png', character: 'eiji.png', spriteIndex: 9, speaker: '衛二', text: 'わかってるよ。俺だって兄貴に死んでもらいたくはない' },
            { bg: 'nightmt.png', character: 'eiji.png', spriteIndex: 0, speaker: '衛二', text: 'ただ、納得したかっただけだ' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 1, speaker: '忠重', text: '勝負はついた。両者とも見事だったぞ' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '家督は護に譲るものとする' },
            { bg: 'nightmt.png', effect: 'whiteout', text: '' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 9, speaker: '護', text: 'これは・・・力が溢れてくる' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '先祖の力がお前の仮面に注がれたのだ' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '今後、椎名家の依頼はお前が指揮をとれ' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 0, speaker: '護', text: 'わかった。でも、医者は続けたい。いいかな' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 1, speaker: '忠重', text: '好きにしろ、お前が当主だ' },
            { bg: 'nightmt.png', character: 'eiji.png', spriteIndex: 6, speaker: '衛二', text: '兄貴、大変だ！　UFOが攻めてきたって報告が！', effect: 'shake', bgm: 'dark' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 2, speaker: '忠重', text: 'はっ、早速だな' },
            { bg: 'nightmt.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'UFOと戦ったことが？' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 2, speaker: '忠重', text: '日常茶飯時だ。我々にとって外来種駆除の様なものよ' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '護、当主としての初仕事だ。UFOを全滅させろ' },
            { bg: 'nightmt.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '就任早々慌ただしいな' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 1, speaker: '護', text: '大丈夫です。忙しいのには慣れてますから' }
        ],
        loss_adv: [ // 負けパターン（STG内で呼び出される）
            { bg: 'nightmt.png', character: 'uraeiji.png', spriteIndex: 2, speaker: '衛二(裏)', text: 'ははははっ！　勝った！　兄貴に勝った！', effect: 'shake', bgm: 'stop' },
            { bg: 'nightmt.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: '椎名くん、残念だが君の運命は確定してしまった', bgm: 'dark' },
            { bg: 'nightmt.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'もはや何度時間を巻き戻しても無駄だろう' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: 'そんな・・・' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 1, speaker: '忠重', text: '護よ・・・落ち込むでない' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: '何だよ、父さん。僕はもう死ぬんだ' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: '放っといてくれ' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '次回はもっとボムを使え' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 8, speaker: '護', text: 'え、なに？　ボム・・・？' },
            { bg: 'nightmt.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '画面上部でボムを使い続けるのだ。そうすれば衛二に勝てる' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 8, speaker: '護', text: 'ちょっと待ってよ、ボムって何のこと・・・' },
            { bg: 'nightmt.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '気にするな。こことはまた別の世界の話さ' },
            { bg: 'nightmt.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: '・・・' }
        ]
    },
    2: {
        stgId: 'kagami', // 敵の構成などは各務ステージを流用
        adv: [
            { bg: 'citypanic.png', character: 'shiina.png', spriteIndex: 0, speaker: '護', text: '確かにUFOが大量に現れてるね', delay: 60, bgm: 'dark' },
            { bg: 'citypanic.png', character: 'kagami.png', spriteIndex: 6, speaker: '各務', text: '・・・あれは!!', effect: 'shake' },
            { bg: 'citypanic.png', character: 'shiina.png', spriteIndex: 8, speaker: '護', text: '各務さん？' },
            { bg: 'citypanic.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: 'うん・・・非常にその・・・申し訳ないんだが' },
            { bg: 'citypanic.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'あれはうちの迎撃装置だ' },
            { bg: 'citypanic.png', character: 'shiina.png', spriteIndex: 9, speaker: '護', text: 'ええ！？', effect: 'shake' },
            { bg: 'citypanic.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: '別件で使ったあと、スイッチを切るのを忘れてしまってな' },
            { bg: 'citypanic.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: 'じゃあ、スイッチを切ってもらえれば止まるんですね' },
            { bg: 'citypanic.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '母艦までたどり着ければな' },
            { bg: 'citypanic.png', character: 'shiina.png', spriteIndex: 7, speaker: '護', text: '母艦・・・無数の戦闘機に守られてますね' },
            { bg: 'citypanic.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '丁度いいじゃないか、護' },
            { bg: 'citypanic.png', character: 'tadashige.png', spriteIndex: 1, speaker: '忠重', text: '先祖の力を引き継いだお前の力、試してみろ' },
            { bg: 'citypanic.png', character: 'shiina.png', spriteIndex: 8, speaker: '護', text: 'いくら何でも多勢に無勢だよ' },
            { bg: 'citypanic.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '家督、衛二に戻してもいいんだぞ' },
            { bg: 'citypanic.png', item: 'mask.png', se: 'vibration.mp3', text: '' }, 
            { bg: 'citypanic.png', character: 'urashiina.png', spriteIndex: 3, speaker: '護(裏)', text: 'ちっ、しゃーねぇな！　行ってくらぁ', effect: 'shake' },
            { bg: 'citypanic.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '大丈夫なのか。うちのシステムはかなり堅牢だぞ' },
            { bg: 'citypanic.png', character: 'tadashige.png', spriteIndex: 1, speaker: '忠重', text: '心配はいらん。あいつは家を継ぐのを拒否していたがな' },
            { bg: 'citypanic.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '才能は、一族随一だ' }
        ], 
        pre_stg: [
            { bg: 'citypanic.png',character: 'urashiina.png', spriteIndex: 2, speaker: '護(裏)', text: '的が・・・的が一杯だ！　うははははっ！', effect: 'shake' },
            { bg: 'citypanic.png',character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '椎名くん・・・なんか随分とハイだな' },
            { bg: 'citypanic.png',character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: '仮面は脳を100％使用すると言われてる' },
            { bg: 'citypanic.png',character: 'tadashige.png', spriteIndex: 1, speaker: '忠重', text: '理性も本能も全部剥き出しになるというわけだ' },
            { bg: 'citypanic.png',character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '椎名くんは普段、色々我慢してるんだな' },
            { bg: 'citypanic.png',character: 'urashiina.png', spriteIndex: 3, speaker: '護(裏)', text: 'ぶっ潰すぞオラァ！', effect: 'shake' },
            { bg: 'citypanic.png',character: 'tadashige.png', spriteIndex: 2, speaker: '忠重', text: 'あいつ、怒らせんように気をつけよう・・・' }
        ], 
        event_adv: [
            { bg: 'cityboss.png', character: 'urashiina.png', spriteIndex: 0, speaker: '護(裏)', text: 'ほう、なかなかデケェじゃねぇか' },
            { bg: 'cityboss.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: '母艦の弾幕は半端ないぞ、椎名くん' },
            { bg: 'cityboss.png', character: 'urashiina.png', spriteIndex: 3, speaker: '護(裏)', text: '弾幕？　見えねぇな、そんなモン' },
            { bg: 'cityboss.png', character: 'urashiina.png', spriteIndex: 2, speaker: '護(裏)', text: '真・言・展・開！', effect: 'shake' }
        ],
        post_stg: [ 
            { bg: 'breakufo2.png', character: 'shiina.png', spriteIndex: 8, speaker: '護', text: 'やった・・・のか？　僕が？', delay: 60, bgm: 'relax' },
            { bg: 'breakufo2.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: 'ああ、やり過ぎたくらいだ' },
            { bg: 'breakufo2.png', character: 'tadashige.png', spriteIndex: 4, speaker: '忠重', text: '護。後始末のコストも考えて動いてもらわねば困るぞ' },
            { bg: 'breakufo2.png', character: 'shiina.png', spriteIndex: 10, speaker: '護', text: 'ご、ごめんなさい、父さん', effect: 'shake' },
            { bg: 'breakufo2.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: 'とはいえ、今回はよしとするかな' },
            { bg: 'breakufo2.png', character: 'shiina.png', spriteIndex: 9, speaker: '護', text: 'えっ！？' },
            { bg: 'breakufo2.png', character: 'tadashige.png', spriteIndex: 1, speaker: '忠重', text: '世に十分知らしめただろうからな、新当主の力を' },
            { bg: 'breakufo2.png', character: 'tadashige.png', spriteIndex: 0, speaker: '忠重', text: 'これから忙しくなるぞ。ははははっ' },
            { bg: 'breakufo2.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: 'なんか・・・すまない' },
            { bg: 'breakufo2.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: '良いんです。僕が自分で選んだ・・・いや' },
            { bg: 'breakufo2.png', character: 'shiina.png', spriteIndex: 0, speaker: '護', text: '自分で選び直した道ですから' },
            { bg: 'breakufo2.png', character: 'kagami.png', spriteIndex: 0, speaker: '各務', text: '潔い男だな、君は' },
            { bg: 'breakufo2.png', character: 'shiina.png', spriteIndex: 1, speaker: '護', text: 'ところで各務さん。これで僕は一年後、死なずに済むのでしょうか' },
            { bg: 'breakufo2.png', character: 'kagami.png', spriteIndex: 9, speaker: '各務', text: 'いや。もちろん、力を得た上で元凶となる相手を倒さなくてはならない' },
            { bg: 'breakufo2.png', character: 'shiina.png', spriteIndex: 7, speaker: '護', text: '元凶ってのは・・・？' },
            { bg: 'breakufo2.png', character: 'kagami.png', spriteIndex: 2, speaker: '各務', text: 'すまない、規定上ここから先の介入はできないんだ' },
            { bg: 'breakufo2.png', character: 'shiina.png', spriteIndex: 4, speaker: '護', text: '自分で探すしかない、か' }
        ]
    },
    3: { adv: [], pre_stg: [], post_stg: [] },
    4: { adv: [], pre_stg: [], post_stg: [] },
    5: { adv: [], pre_stg: [], post_stg: [] },
    6: { adv: [], pre_stg: [], post_stg: [] }
};
